plugin: azure.azcollection.azure_rm
auth_source: auto
subscription_id: 79560fde-5831-481d-8c3c-e812ef5046e5
plain_host_names: true
include_vmss_resource_groups:
  - '*'
conditional_groups:
  production: true
exclude_host_filters:
- powerstate != 'running'
hostvar_expressions:
  ansible_ssh_private_key_file: "'~/.ssh/id_bink_azure_terraform'"
  ansible_user: "'terraform'"
  ansible_connection: "'ssh'"
  ansible_ssh_common_args: "'-o ProxyCommand=\"ssh -W %h:%p bastion\"'"
